# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.domain_listener:
    class: AppBundle\EventSourcing\DomainEventListener
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_listener, event: kernel.controller }

  app.domain_notifier:
    class: AppBundle\EventSourcing\DomainEventNotifier
    arguments: ["@doctrine.orm.entity_manager"]

  app.repair_projector:
    class: AppBundle\EventSourcing\RepairProjectorListener
    arguments: ["@doctrine.orm.entity_manager"]